### ISSUE TITLE
Comparison with CTRE

### ISSUE THREAD

**Issue by matbech** [iulian-rusu/mregex#6]
How does this library compare with CTRE?
Thank you.

**Comment by iulian-rusu** [comment]
Performance-wise it is pretty similar to CTRE. Some patterns are a bit faster, others a bit slower, depending on how the compiler will optimize the code. 
Regarding the implementation, the matching algorithm is slightly different and a bit more complex, but it is able to match some patterns that CTRE is known to have issues with ([example](https://github.com/hanickadot/compile-time-regular-expressions/issues/257)). 
Also, this is mostly a hobby side-project so there are still some missing things like unicode support which may be a deal-breaker for some people.
